telegraf:
  image: apicht/rpi-telegraf
  volumes:
    - /data/docker/telegraf:/data
  links:
    - influxdb
influxdb:
  image: pithings/rpi-influxdb
  ports:
    - 8086:8086
    - 8083:8083
  volumes:
    - /data/docker/influxdb:/data
grafana:
  image: pithings/rpi-grafana
  volumes:
    - /data/docker/grafana/data:/var/lib/grafana
    - /data/docker/grafana/log:/var/log/grafana
  ports:
    - "3000:3000"
