version: '2'

services:
  telegraf:
    image: apicht/rpi-telegraf
    links:
      - influxdb
    environment:
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc
      HOST_MOUNT_PREFIX: /rootfs
    volumes:
      - /:/rootfs:ro
      - /data/docker/telegraf:/data
  influxdb:
    image: pithings/rpi-influxdb
    environment:
      PRE_CREATE_DB: telegraf
    ports:
      - 8086:8086
      - 8083:8083
    volumes:
      - /data/docker/influxdb:/var/lib/influxdb
  grafana:
    image: pithings/rpi-grafana
    volumes:
      - /data/docker/grafana/data:/var/lib/grafana
      - /data/docker/grafana/log:/var/log/grafana
    ports:
      - "3000:3000"
